# Generated by Django 5.1.3 on 2024-12-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=10),
        ),
    ]
