# Generated by Django 5.1.3 on 2024-12-03 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockmovement_adjustment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='purchaseitem',
            name='line_total',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='line_total',
        ),
    ]
