# Generated by Django 5.1.3 on 2024-12-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_sale_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
