# Generated by Django 5.1.3 on 2024-12-09 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0007_alter_purchaseitem_quantity_alter_saleitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reference',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
