# Generated by Django 5.1.3 on 2024-12-09 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_stockmovement_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
