# Generated by Django 5.1.3 on 2024-12-11 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='is_paid',
        ),
    ]
