# Generated by Django 5.1.3 on 2024-12-16 17:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_stockmovement_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseitem')),
            ],
        ),
        migrations.CreateModel(
            name='LotConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date_consumed', models.DateTimeField(default=django.utils.timezone.now)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.lot')),
            ],
        ),
    ]
