# Generated by Django 5.1.3 on 2024-12-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_transaction_options_lot_lotconsumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='batch_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
