# Generated by Django 5.1.3 on 2024-12-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_rename_quantity_lot_quantity_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lot',
            name='purchase_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchaseitem'),
        ),
    ]
