# Generated by Django 5.1.3 on 2024-12-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_lot_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotconsumption',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
            preserve_default=False,
        ),
    ]
