# Generated by Django 5.1.3 on 2024-12-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_lotconsumption_selling_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lot',
            options={'ordering': ['date_received', 'id']},
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='unit_price',
            new_name='cost_per_unit',
        ),
    ]
