# Generated by Django 5.1.3 on 2024-12-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_lot_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='cost_per_unit',
            new_name='unit_cost',
        ),
    ]
