# Generated by Django 5.1.3 on 2024-12-18 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_rename_cost_per_unit_lot_unit_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotconsumption',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.saleitem'),
        ),
    ]
