# Generated by Django 5.1.3 on 2024-12-19 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_lotconsumption_sale_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='is_initial_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lotconsumption',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='inventory.saleitem'),
        ),
    ]
