# Generated by Django 5.1.3 on 2024-12-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_cutting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutting',
            name='weight_loss',
        ),
        migrations.AddField(
            model_name='cutting',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cutting',
            name='quantity_reduction',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
