# Generated by Django 5.1.3 on 2024-12-19 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_remove_cutting_weight_loss_cutting_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lot',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='lot',
            name='unit_cost',
        ),
    ]
