# Generated by Django 5.1.3 on 2024-12-20 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_lot_quantity_received_remove_lot_unit_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cutting',
            old_name='quantity_reduction',
            new_name='ending_weight',
        ),
        migrations.RenameField(
            model_name='cutting',
            old_name='quantity',
            new_name='starting_weight',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_items', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='inventory.product'),
        ),
    ]
