# Generated by Django 5.1.3 on 2024-12-23 06:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_meatprocessing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('CUT', 'Cut'), ('SLICE', 'Slice'), ('MINCE', 'Mince'), ('PACKAGE', 'Package')], max_length=20)),
                ('starting_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ending_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.lot')),
            ],
        ),
        migrations.DeleteModel(
            name='MeatProcessing',
        ),
    ]
