# Generated by Django 5.1.3 on 2024-12-23 06:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0027_meatprocess_delete_meatprocessing'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('date_consumed', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.lot')),
            ],
        ),
        migrations.DeleteModel(
            name='LotConsumption',
        ),
    ]
