# Generated by Django 5.1.3 on 2024-12-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_lotmovement_delete_lotconsumption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotmovement',
            old_name='date_consumed',
            new_name='date',
        ),
        migrations.AddField(
            model_name='lotmovement',
            name='movement_type',
            field=models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJ', 'Adjustment')], default='OUT', max_length=10),
            preserve_default=False,
        ),
    ]
