# Generated by Django 5.1.3 on 2024-12-27 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_rename_date_consumed_lotmovement_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='predict_sales',
            field=models.BooleanField(default=True),
        ),
    ]
