# Generated by Django 5.1.3 on 2024-12-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_product_predict_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='predict_sales',
            new_name='predict_demand',
        ),
    ]
