# Generated by Django 5.1.3 on 2024-12-30 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_rename_lot_stockbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbatch',
            name='purchase_item',
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='purchase_line_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='inventory.purchaseitem'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='stock_adjustment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='inventory.stockadjustment'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='stock_conversion',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='inventory.stockconversion'),
        ),
        migrations.AddField(
            model_name='stockconversion',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
