# Generated by Django 5.1.3 on 2024-12-30 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0034_remove_stockbatch_purchase_item_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LotMovement',
            new_name='BatchMovement',
        ),
    ]
