# Generated by Django 5.1.3 on 2024-12-30 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_rename_lotmovement_batchmovement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batchmovement',
            old_name='lot',
            new_name='batch',
        ),
        migrations.RenameField(
            model_name='cutting',
            old_name='lot',
            new_name='batch',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='purchase_line_item',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='stock_adjustment',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='stock_conversion',
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='product',
            field=models.ForeignKey(default=203, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='quantity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
