# Generated by Django 5.1.3 on 2024-12-30 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_rename_lot_batchmovement_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cutting',
        ),
    ]
