# Generated by Django 5.1.3 on 2024-12-31 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0037_delete_cutting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batchmovement',
            options={'verbose_name_plural': 'Batch Movements'},
        ),
        migrations.AlterModelOptions(
            name='stockadjustment',
            options={'verbose_name_plural': 'Stock Adjustments'},
        ),
        migrations.AlterModelOptions(
            name='stockbatch',
            options={'ordering': ['date_received', 'id'], 'verbose_name_plural': 'Stock Batches'},
        ),
        migrations.AlterModelOptions(
            name='stockconversion',
            options={'verbose_name_plural': 'Stock Conversions'},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name_plural': 'Stock Movements'},
        ),
        migrations.AlterUniqueTogether(
            name='stockmovement',
            unique_together={('content_type', 'object_id', 'movement_type')},
        ),
    ]
