# Generated by Django 5.1.3 on 2025-01-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0038_alter_batchmovement_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockmovement',
            unique_together={('content_type', 'object_id', 'movement_type', 'date')},
        ),
    ]
