# Generated by Django 5.1.3 on 2025-01-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0039_alter_stockmovement_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbatch',
            name='product',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockbatch',
            name='unit_cost',
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
