# Generated by Django 5.1.3 on 2025-01-04 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_remove_stockbatch_product_remove_stockbatch_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockconversion',
            name='from_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='inventory.product'),
        ),
        migrations.AlterField(
            model_name='stockconversion',
            name='to_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='inventory.product'),
        ),
    ]
