# Generated by Django 5.1.3 on 2025-01-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_alter_batchmovement_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockadjustment',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockconversion',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
    ]
