# Generated by Django 5.1.3 on 2025-02-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='purchase_price',
            new_name='unit_cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='unit_price',
        ),
    ]
