# Generated by Django 5.1.3 on 2025-02-18 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0047_alter_product_unit_cost_alter_product_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockconversion",
            name="to_product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversions_to",
                to="inventory.product",
            ),
        ),
    ]
