# Generated by Django 5.1.3 on 2025-02-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0048_alter_stockconversion_to_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockbatch",
            name="consumed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["date_received", "consumed"],
                name="inventory_s_date_re_240eb0_idx",
            ),
        ),
    ]
