# Generated by Django 5.1.3 on 2025-02-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0049_stockbatch_consumed_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stockbatch",
            name="inventory_s_date_re_240eb0_idx",
        ),
        migrations.RenameField(
            model_name="stockbatch",
            old_name="consumed",
            new_name="is_exhausted",
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["date_received", "is_exhausted"],
                name="inventory_s_date_re_fa24d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="inventory_s_content_d429d4_idx",
            ),
        ),
    ]
