# Generated by Django 5.1.3 on 2025-02-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0050_remove_stockbatch_inventory_s_date_re_240eb0_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["date_received"], name="inventory_s_date_re_0891b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["is_exhausted"], name="inventory_s_is_exha_02a2f0_idx"
            ),
        ),
    ]
