# Generated by Django 5.1.3 on 2025-02-20 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0051_stockbatch_inventory_s_date_re_0891b3_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stockbatch",
            name="inventory_s_date_re_fa24d3_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockbatch",
            name="inventory_s_is_exha_02a2f0_idx",
        ),
        migrations.RemoveField(
            model_name="stockbatch",
            name="is_exhausted",
        ),
    ]
