# Generated by Django 5.1.3 on 2025-02-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("inventory", "0052_remove_stockbatch_inventory_s_date_re_fa24d3_idx_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="batchmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="positive_quantity"
            ),
        ),
    ]
