# Generated by Django 5.1.3 on 2025-03-01 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0054_alter_batchmovement_id_alter_expense_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchmovement",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
